### ISSUE TITLE
Some issues with text alignment on mobile

### ISSUE THREAD

**Issue by andys8** [simple-haskell/simple-haskell-website#2]
Hey, great approach :)

There are currently some glitches on mobile. The size is scrolling horizontally because the text has too much width and text spacing is misaligned.

![Screenshot_20200109-093539](https://user-images.githubusercontent.com/13085980/72051490-b1ba2780-32c3-11ea-8191-229bd71fcc65.png)
![Screenshot_20200109-093449](https://user-images.githubusercontent.com/13085980/72051492-b1ba2780-32c3-11ea-884d-6fe46af7dcb4.png)

Android 10, Chrome 79 / Brave

**Comment by simple-haskell-admin** [comment]
Thanks for the bug report.  I think it should be fixed now.
