### ISSUE TITLE
Misquotation

### ISSUE THREAD

**Issue by sdiehl** [simple-haskell/simple-haskell-website#5]
I think the quote from me [here](https://github.com/simple-haskell/simple-haskell-website/commit/f18101c231f25a9b48435125eec63a746a7bbf86#diff-eae600270579316beb8b8d9b9a5732d4R162) is out of context.

What I said in my talk is that *if* the language continues to evolve without bound then the semantics of all language interactions will exceed human capacity, which is different than the quote here which presents that as *currently* being the case which is not something I'm on the record of saying.

**Comment by simple-haskell-admin** [comment]
I removed the quote.  Apologies for the misrepresentation.
